### ISSUE TITLE
Call ninja automatically if bf is called without any arguments

### ISSUE THREAD

**Issue by jimon** [beardsvibe/buildfox#154]
So we don't need to type `bf && ninja` but just `bf`

**Comment by den-mentiei** [comment]
In generated makefile we are using `buildfox.py` (without args) as a configure rule - it will result in `ninja` call.

We need to do something with it - maybe use some argument for it.

**Comment by jimon** [comment]
Might be something like `--do-not-run-ninja` :/

**Comment by den-mentiei** [comment]
`--just-generate`? :)

**Comment by jimon** [comment]
That's better :+1:

**Comment by jimon** [comment]
It's quite buggy on Windows atm:

```
C:\work\try_material>bfd
b'[1/7] cc src/css-micro-parser/test.c'
b'[2/7] cc src/aheasing/easing.c'
b'[3/7] cc src/material_gl/material_gl.c'
b'[4/7] cc src/tigr/tigr.c'
b'[5/7] cc src/glew/glew.c'
b'[6/7] cc src/main.c'
b'[7/7] link build/app.exe'
b'FAILED: build/app.exe'
b'cl /nologo @build/app.exe.rsp /MT /link  /LIBPATH:src/libcurl/static-release-x64  /out:build/app.exe'
b'LINK : warning LNK4031: no subsystem specified; CONSOLE assumed'
b'main.obj : error LNK2019: unresolved external symbol _curl_easy_strerror referenced in function _main'
b'main.obj : error LNK2019: unresolved external symbol _curl_easy_init referenced in function _main'
b'main.obj : error LNK2019: unresolved external symbol _curl_easy_setopt referenced in function _main'
b'main.obj : error LNK2019: unresolved external symbol _curl_easy_perform referenced in function _main'
b'main.obj : error LNK2019: unresolved external symbol _curl_easy_cleanup referenced in function _main'
b"src/libcurl/static-release-x64\\libcurl_a.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'X86'"
b'build/app.exe : fatal error LNK1120: 5 unresolved externals'
b'ninja: build stopped: subcommand failed.'
Traceback (most recent call last):
  File "C:\work\buildfox\buildfox.py", line 497, in <module>
    main()
  File "C:\work\buildfox\buildfox.py", line 491, in main
    sys.exit(run_command("ninja"))
  File "C:\work\buildfox\buildfox.py", line 320, in run_command
    output = process.stdout.readline()
KeyboardInterrupt
```

The worst - it gets stuck in the end.

**Comment by den-mentiei** [comment]
What is bug about here and what do you mean by 'stuck'?

**Comment by jimon** [comment]
1) `b'ninja: build stopped: subcommand failed.'` is just wrong, basically stdout bytes are not converted to string, it should print `ninja: build stopped: subcommand failed.` instead.
2) bf just get struck waiting for something after it prints `b'ninja: build stopped: subcommand failed.'`, basically at this point ninja is already finished, but bf is waiting for something.

**Comment by jimon** [comment]
Guess it's fixed.
